import type { Metadata } from "next";
import '../scss/global.scss'
import Header from "@/components/elements/Header";
import Footer from "@/components/elements/Footer";
import MobileBottom from "@/components/elements/MobileBottom";


export const metadata: Metadata = {
  title: "Willbetreut",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body >
        <div className="wrapper">
          <Header />
          <main className="main">
            {children}
          </main>
          <Footer />
        </div>
        <MobileBottom />

      </body>
    </html>
  );
}
